### ISSUE TITLE
How to mark square as bomb?

### ISSUE THREAD

**Issue by oskar** [axelo/elm-mines#1]
Right-clicking doesn't work (at least not in Chrome 70.0.3538.77 on MacOS 10.13.6.

**Comment by axelo** [comment]
Currently you have to shift + click to mark.

Still have to figure at a useful interaction that also work great on touch devices

**Comment by oskar** [comment]
Ah, thanks. Tried ctrl and cmd modifiers but not shift.. 🙄

**Comment by axelo** [comment]
Will be resolved in #3
